<header id="top">
    <!-- 1-1. 로고 -->
    <h1 class="tit">
        <a href="index.php">
            <!-- 글자 -->
            <img src="images/mlogo_7.png" alt="my item" id="mytit">
            <!-- 빨간공 -->
            <img src="images/mlogo_6.png" alt="빨간공" id="rball">
            <!-- 카멜레온박스 -->
            <div id="cambx">
                <!-- 혀박스 -->
                <span id="tung"></span>
                <!-- 카멜레온 -->
                <img src="images/mlogo_05.png" alt="카멜레온" id="cam">
            </div>
        </a>
    </h1>
    <!-- 1-2. GNB메뉴 -->
    <nav class="gnb">
        <ul>
            <li>
                <a href="#">Home</a>
            </li>
            <li>
                <a href="#">디바이스</a>
                <!-- 서브메뉴 -->
                <ol class="smenu">
                    <li>
                        <a href="#">스마트폰</a>
                    </li>
                    <li>
                        <a href="#">태블릿PC</a>
                    </li>
                    <li>
                        <a href="#">노트북</a>
                    </li>
                </ol>
            </li>
            <li>
                <a href="#">패션</a>
                <!-- 서브메뉴 -->
                <ol class="smenu">
                    <li>
                        <a href="#">가방</a>
                    </li>
                    <li>
                        <a href="#">시계</a>
                    </li>
                    <li>
                        <a href="#">구두</a>
                    </li>
                </ol>
            </li>
            <li>
                <a href="#">프로필</a>
            </li>
        </ul>
    </nav>
    <!-- 1-3. 공통메뉴 -->
    <ul class="tmenu">
        <li>
            <a href="#">회원가입</a>
        </li>
        <li>
            <a href="#">로그인</a>
        </li>
        <li>
            <a href="#">게시판</a>
        </li>
        <li>
            <a href="#">오시는길</a>
        </li>
    </ul>
    <!-- 1-4.sns메뉴 -->
    <ul class="sns">
        <li>
            <a href="#">
                <span class="ir">트위터바로가기</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="ir">인스타그램바로가기</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="ir">페이스북바로가기</span>
            </a>
        </li>
    </ul>
</header>